services:
  - type: web
    name: financial-analyzer
    env: python
    region: oregon
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr tesseract-ocr-eng
      pip install -r requirements.txt
    startCommand: gunicorn --workers 2 --timeout 1800 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: false
